steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:$COMMIT_SHA', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:latest', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:latest']

  # 3. Update the Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'aozora-importer'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--update-secrets'
      - 'ALGOLIA_APP_ID=ALGOLIA_APP_ID:latest,ALGOLIA_ADMIN_KEY=ALGOLIA_ADMIN_KEY:latest'

substitutions:
  _REGION: asia-northeast1

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/aozora/importer:latest'
