import os
import re

# Original source: http://x0213.org/codetable/jisx0213-2004-std.txt


def main():
    """Generate the gaiji table from the JIS X 0213 to Unicode mapping table."""
    table_path = "jisx0213-2004-std.txt"
    output_path = "aozora_data/sjis_to_utf8/gaiji_table.py"

    if not os.path.exists(table_path):
        # Try finding it in the root if we are running from scripts/
        if os.path.exists(os.path.join("..", table_path)):
            table_path = os.path.join("..", table_path)
        else:
            print(f"Error: {table_path} not found.")
            return

    gaiji_map = {}
    with open(table_path, encoding="utf-8", errors="ignore") as f:
        # Regex adapted from converter.py: (\d-\w{4})\s+U\+(\w{4})
        ms = (re.match(r"(\d-\w{4})\s+U\+(\w{4})", line) for line in f if line and line[0] != "#")
        for m in ms:
            if m:
                gaiji_map[m[1]] = chr(int(m[2], 16))

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# This file is auto-generated by scripts/generate_gaiji_table.py\n")
        f.write("# Do not edit manually.\n\n")
        f.write("# ruff: noqa: RUF001\n")
        f.write("GAIJI_TABLE = {\n")
        for k, v in gaiji_map.items():
            # repr(v) will properly escape chars if needed, but usually it's just a quote
            # We want to keep the file valid python.
            f.write(f"    '{k}': {v!r},\n")
        f.write("}\n")

    print(f"Generated {output_path} with {len(gaiji_map)} entries.")


if __name__ == "__main__":
    main()
